export declare const PLUGIN_TYPE = "ReactNative";
export declare const PLUGIN_VERSION = "3.0.0";
export declare const ANDROID_SDK_VERSION = "8.4.0";
export declare const IOS_SDK_VERSION = "8.4.0";
export declare const BANNER_WIDTH = 320;
export declare const BANNER_HEIGHT = 50;
export declare const LARGE_WIDTH = 320;
export declare const LARGE_HEIGHT = 90;
export declare const MEDIUM_RECTANGLE_WIDTH = 300;
export declare const MEDIUM_RECTANGLE_HEIGHT = 250;
export declare const SIZE_BANNER_LABEL = "BANNER";
export declare const SIZE_LARGE_LABEL = "LARGE";
export declare const SIZE_MEDIUM_RECTANGLE_LABEL = "MEDIUM_RECTANGLE";
export declare const SIZE_CUSTOM_LABEL = "CUSTOM";
//# sourceMappingURL=IronSourceConstants.d.ts.map